# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: default
steps:
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/CSproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/CSproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/CSproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/CSproj'
    publishWebProjects: true